def test_fail():
    assert 1
